config/routes.rb
Rails.application.routes.draw do
  resources :payment_links
  resource :session
  resources :passwords, param: :token
  resource :registration,  only: %i[new create]
  resources :profiles, param: :username
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :username, presence: true, uniqueness: true
  validates :nickname, presence: true
  validates :bio, length: { maximum: 500 }
  validates :user, uniqueness: true
  has_many :payment_links, dependent: :destroy
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_authentication, only: %i[ new create edit update ]
  before_action :resume_session, only: %i[ show ]

  def new
    @profile = Profile.new
    @user = Current.user
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = Current.user

    if @profile.save
      redirect_to profile_path(@profile.username), notice: "Profile created successfully."
    else
      @user = Current.user
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
      @profile = Profile.find_by(username: params[:username])
      @user = Current.user
      # @payment_links = @profile.paymentlinks.includes(:payment_platform)
      @payment_links = @profile.payment_links
      if !@profile
        raise ActiveRecord::RecordNotFound, "Not Found"
      end
  end

  def edit
    @profile = Current.user.profile
  end

  def update
    @profile = Current.user.profile
    if @profile.update(profile_params)
      redirect_to profile_path(@profile.username), notice: "Profile updated successfully."
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:bio, :username, :nickname)
  end
end

app/views/profiles/edit.html.erb
<% content_for :title, "Edit Profile" %>

<div class="mx-auto md:w-2/3 w-full">
  <% if alert = flash[:alert] %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
  <% end %>

  <% if notice = flash[:notice] %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl mb-5">Edit Profile</h1>

  <%= form_with model: @profile, url: profile_path(@profile), method: :patch, class: "contents" do |form| %>
    <div class="my-4">
      <%= form.label :nickname, class: "block text-gray-700" %>
      <%= form.text_field :nickname, required: true, autofocus: true, placeholder: "Enter your nickname", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full" %>
    </div>

    <div class="my-4">
      <%= form.label :username, class: "block text-gray-700" %>
      <%= form.text_field :username, required: true, placeholder: "Enter your username", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full" %>
    </div>

    <div class="my-4">
      <%= form.label :bio, class: "block text-gray-700" %>
      <%= form.text_area :bio, placeholder: "Enter your bio", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full" %>
    </div>

    <div class="col-span-6 sm:flex sm:items-center sm:gap-4">
      <div class="inline">
        <%= form.submit "Update Profile", class: "rounded-lg py-2 px-4 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <% if alert = flash[:alert] %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
  <% end %>

  <% if notice = flash[:notice] %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl mb-5">Create Profile</h1>

  <%= form_with model: @profile, url: profiles_path, class: "contents" do |form| %>
    <div class="my-4">
      <%= form.label :nickname, class: "block text-gray-700" %>
      <%= form.text_field :nickname, required: true, autofocus: true, placeholder: "Enter your nickname", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full" %>
    </div>

    <div class="my-4">
      <%= form.label :username, class: "block text-gray-700" %>
      <%= form.text_field :username, required: true, placeholder: "Enter your username", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full" %>
    </div>

    <div class="my-4">
      <%= form.label :bio, class: "block text-gray-700" %>
      <%= form.text_area :bio, placeholder: "Enter your bio", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full" %>
    </div>

    <div class="col-span-6 sm:flex sm:items-center sm:gap-4">
      <div class="inline">
        <%= form.submit "Create Profile", class: "rounded-lg py-2 px-4 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<h1>Profile</h1>

<div class="relative">
    <% if @profile.user == Current.user %>
        <%= link_to 'Edit Profile', edit_profile_path(@profile), class: 'absolute top-0 right-0 btn btn-primary' %>
    <% end %>
</div>

<div class="profile mb-6">
    <h2 class="text-xl font-semibold"><%= link_to @profile.nickname, profile_path(@profile) %></h2>
    <p>Email: <%= @profile.username %></p>
    <p>Bio: <%= @profile.bio %></p>
</div>

<div class="payment-links mt-5">
    <div class="flex justify-between items-center mb-5">
        <h1 class="font-bold text-4xl">Payment Links</h1>
        <%= link_to "New payment link", new_payment_link_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
    </div>
    <% if @profile.payment_links.any? %>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <% @profile.payment_links.each do |payment_link| %>
                <div class="border rounded-lg shadow-md p-4 bg-white dark:bg-gray-800 h-48 flex flex-col justify-between">
                    <div class="flex items-center">
                        <%# Display the logo for the payment platform %>
                        <%= image_tag "logos/#{payment_link.payment_platform.logo_url}", alt: payment_link.payment_platform.name, class: "h-12 w-12 mr-4" %>
                        <p class="text-lg font-semibold"><%= payment_link.payment_platform.name %></p>
                    </div>
                    <p class="mt-4"><strong>PayID:</strong> <%= payment_link.payid %></p>
                    <div class="mt-2">
                        <%= link_to 'View', payment_link_path(payment_link), class: 'text-blue-500 hover:underline' %>
                    </div>
                </div>
            <% end %>
        </div>
    <% else %>
        <p>No payment links found for this profile.</p>
    <% end %>
</div>