config/routes.rb
Rails.application.routes.draw do
  resources :payment_links
  resource :session
  resources :passwords, param: :token
  resource :registration,  only: %i[new create]
  resources :profiles, param: :username
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
end

app/models/payment_link.rb
class PaymentLink < ApplicationRecord
  belongs_to :profile
  belongs_to :payment_platform
end

app/controllers/payment_links_controller.rb
class PaymentLinksController < ApplicationController
  before_action :set_payment_link, only: %i[ show edit update destroy ]
  before_action :set_payment_platforms, only: %i[ new edit create update ]
  before_action :require_authentication, only: %i[ new edit create update destroy ]

  # GET /payment_links or /payment_links.json
  def index
    @payment_links = PaymentLink.all
  end

  # GET /payment_links/1 or /payment_links/1.json
  def show
  end

  # GET /payment_links/new
  def new
    @payment_link = PaymentLink.new
  end

  # GET /payment_links/1/edit
  def edit
  end

  # POST /payment_links or /payment_links.json
  def create
    @payment_link = PaymentLink.new()
    @payment_link.profile = Current.user.profile
    Rails.logger.debug("payment_link_params: #{payment_link_params[:payment_platform_id]}")
    @payment_link.payment_platform = PaymentPlatform.find(payment_link_params[:payment_platform_id])
    @payment_link.payid = payment_link_params[:payid]


    respond_to do |format|
      if @payment_link.save
        format.html { redirect_to @payment_link, notice: "Payment link was successfully created." }
        format.json { render :show, status: :created, location: @payment_link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_links/1 or /payment_links/1.json
  def update
    # @payment_link.payment_platform = PaymentPlatform.find(payment_link_params[:paymentplatform_id])
    respond_to do |format|
      if @payment_link.update(payment_link_params)
        format.html { redirect_to @payment_link, notice: "Payment link was successfully updated." }
        format.json { render :show, status: :ok, location: @payment_link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_links/1 or /payment_links/1.json
  def destroy
    @payment_link.destroy!

    respond_to do |format|
      format.html { redirect_to payment_links_path, status: :see_other, notice: "Payment link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_payment_platforms
      @payment_platforms = PaymentPlatform.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_link
      @payment_link = PaymentLink.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def payment_link_params
      params.expect(payment_link: [ :payment_platform_id, :payid ])
    end
end

app/helpers/payment_links_helper.rb
module PaymentLinksHelper
end

app/views/payment_links/_form.html.erb
<%= form_with(model: payment_link, class: "contents") do |form| %>
  <% if payment_link.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(payment_link.errors.count, "error") %> prohibited this payment_link from being saved:</h2>

      <ul class="list-disc ml-6">
        <% payment_link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :paymentplatform_id %>
    <%
=begin%>
 <%= form.collection_select :paymentplatform_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": payment_link.errors[:paymentplatform_id].none?, "border-red-400 focus:outline-red-600": payment_link.errors[:paymentplatform_id].any?}] %> 
<%
=end%>
    <%= form.collection_select :payment_platform_id, @payment_platforms, :id, :name, prompt: "Select Payment Platform" %>
  </div>

  <div class="my-5">
    <%= form.label :payid %>
    <%= form.text_field :payid, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": payment_link.errors[:payid].none?, "border-red-400 focus:outline-red-600": payment_link.errors[:payid].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/payment_links/_payment_link.html.erb
<div id="<%= dom_id payment_link %>" class="my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Paymentplatform:</strong>
    <%= payment_link.payment_platform.name %>


  </div>
  <div>
    <strong class="block font-medium mb-1">Payid:</strong>
    <%= payment_link.payid %>
  </div>
</div>

app/views/payment_links/edit.html.erb
<% content_for :title, "Editing payment link" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing payment link</h1>

  <%= render "form", payment_link: @payment_link %>

  <%= link_to "Show this payment link", @payment_link, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to payment links", payment_links_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/payment_links/index.html.erb
<% content_for :title, "Payment links" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Payment links</h1>
    <%= link_to "New payment link", new_payment_link_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="payment_links" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @payment_links.any? %>
      <% @payment_links.each do |payment_link| %>
        <div class="flex justify-between items-center">
          <%= render payment_link %>
          <div class="space-x-2">
            <%= link_to "Show", payment_link, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_payment_link_path(payment_link), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="inline-block">
              <%= button_to "Destroy", payment_link, method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No payment links found.</p>
    <% end %>
  </div>
</div>

app/views/payment_links/new.html.erb
<% content_for :title, "New payment link" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New payment link</h1>

  <%= render "form", payment_link: @payment_link %>

  <%= link_to "Back to payment links", payment_links_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/payment_links/show.html.erb
<% content_for :title, "Showing payment link" %>

<div class="md:w-2/3 w-full dark:bg-gray-900">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl dark:text-grey-1000">Showing payment link</h1>

  <%= render @payment_link %>

  <%= link_to "Edit this payment link", edit_payment_link_path(@payment_link), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to payment links", payment_links_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this payment link", @payment_link, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>